- hosts: localhost
  connection: local

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: true
        upgrade: 'yes'
        autoclean: true
        autoremove: true
      changed_when: False
  
  tasks:
  - include: tasks/main.yml