---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update Packages
      become: true
      apt:
        update_cache: true
        upgrade: 'yes'
        autoclean: true
        autoremove: true
      changed_when: False
  
  tasks:
  - include: tasks/main.yml