---
- name: Set pyenv global virtualenv '{{ pyenv_global }}'
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} virtualenv {{pyenv_global}} lewagon"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"