---
- name: Get current global version
  become: true
  become_user: "{{base_user}}"
  shell: " {{ pyenv_bin_path }} global "
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"
  register: pyenv_global_version
  changed_when: false

- name: Set pyenv_global_active fact
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.set_fact:
    pyenv_global_active: "{{ pyenv_global_version.stdout_lines |
      join(' ') | trim() }}"

- name: Check if 'system' version is available 
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} versions"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  register: pyenv_versions
  changed_when: false
  failed_when: false
  when: "'system' in pyenv_global"

- name: Set pyenv global version to '{{ pyenv_global }}'
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} global 3.10.6 system"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  when: "pyenv_global is defined and pyenv_global_active != pyenv_global"