---
- name: Upgrade Pip in virtual environment
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pip_install_environment }} install --upgrade pip"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"
  
- name: Install specified python requirements in indicated (virtualenv)
    ansible.builtin.pip:
      requirements: https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/linux.txt
      virtualenv: "{{ pyenv_install_environment }}"

- name: Install Packages in virtual environment
  become: true
  become_user: "{{base_user}}"
  shell: |
    {{ jupyter_install_environment }} contrib nbextension install --user
    {{ jupyter_install_environment }} nbextension enable toc2/main
    {{ jupyter_install_environment }} nbextension enable collapsible_headings/main
    {{ jupyter_install_environment }} nbextension enable spellchecker/main
    {{ jupyter_install_environment }} nbextension enable code_prettify/code_prettify
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"   
  register: jupyter_output