---
- name: Upgrade Pip in virtual environment
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pip_install_environment }} install --upgrade pip"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"
  
- name: Install Packages in virtual environment
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pip_install_environment }} install -r https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/linux.txt"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"

- name: Basic Debug
  debug:
    msg: "{{pip_output.stdout_lines}}"  

- name: Install Packages in virtual environment
  become: true
  become_user: "{{base_user}}"
  shell: |
    jupyter contrib nbextension install --user
    jupyter nbextension enable toc2/main
    jupyter nbextension enable collapsible_headings/main
    jupyter nbextension enable spellchecker/main
    jupyter nbextension enable code_prettify/code_prettify
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{ install_shell }}"   
  register: jupyter_output

- name: Basic Debug
  debug:
    msg: "{{jupyter_output.stdout_lines}}"