---
- name: get vars
  include_vars:
    dir: ../../vars

- name: source.zshrc
  become: true
  become_user: "{{ base_user }}"
  shell: 
    cmd: |
      "source {{ pyenv_zshrc_path }}"

- debug:
    var: lookup('env', 'SHELL')

- name: python source
  become: true
  become_user: "{{ base_user }}"
  shell: 
    cmd: |
      "exec /usr/bin/zsh"
      "{{ pyenv_bin_path }} root"
  environment:
    PATH: "/usr/bin/zsh:{{ ansible_env.SHELL }}" 
  register: pyenv_root_output

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: 
    cmd: |
      "exec {{ pyenv_bin_path }}"
      "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"