---
- name: get vars
  include_vars:
    dir: ../../vars

- name: source.zshrc
  become: true
  become_user: "{{ base_user }}"
  shell: "source {{ pyenv_zshrc_path }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  environment:
    PATH: "/bin/zsh:{{ ansible_env.SHELL }}" 
    
- name: set SHELL
  become: true
  become_user: "{{ base_user }}"
  ansible.builtin.set_fact:
    shell: "{{ lookup('env','SHELL') }}"
  args:
    executable: /bin/zsh

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment:
    PATH: "/bin/zsh:{{ ansible_env.SHELL }}"