---
- name: get vars
  include_vars:
    dir: ../../vars

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- name: Basic usage
  become_user: "{{base_user}}"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'USER') }}"

- name: Basic usage
  become_user: "{{base_user}}"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'SHELL') }}"

- name: Check if .pyenv exists as directory
  become_user: "{{base_user}}"
  ansible.builtin.stat:
    path: $HOME/.pyenv
  register: stat_home_pyenv_result

- name: Install Python interpreters
  become_user: "{{base_user}}"
  ansible_become_method: enable
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{install_shell}}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"