---
- name: get vars
  include_vars:
    dir: ../../vars

- name: Debug variables
  become: true
  become_user: "{{base_user}}"
  debug:
    msg: "{{ pyenv_bin_path }} install {{ item }}"
  with_items: "{{ pyenv_python_versions }}"

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "{{ pyenv_root }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"