---
- name: get vars
  include_vars:
    dir: ../../vars

- name: Check if .pyenv exists as directory
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.stat:
    path: $HOME/.pyenv
  register: stat_home_pyenv_result

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  with_items: "{{ pyenv_python_versions }}"
  when: not stat_home_pyenv_result.stat.exists

- name: Move all shims files
  become: true
  become_user: "{{base_user}}"
  command: mv "{{ item }}" $HOME/.config/pyenv/shims
  with_fileglob: "$HOME/.pyenv/shims/*"
  args:
    warn: false
  
- name: Move version to destination
  become: true
  become_user: "{{base_user}}"
  command: "mv $HOME/.pyenv/versions/{{ item }} $HOME/.config/pyenv/versions/{{ item }}"
  with_items: "{{ pyenv_python_versions }}"

  - name: Remove directory recursively
  become: true
  become_user: "{{base_user}}"
  file:
    path: /path/to/directory
    state: absent
    recurse: yes