---
- name: get vars
  include_vars:
    dir: ../../vars

- name: get the username running the deploy
  become: true
  become_user: "{{base_user}}"
  shell: whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- name: Basic usage
  become: true
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'SUDO_USER') }}"
  become_user: "{{base_user}}"

- name: Basic usage
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'SHELL') }}"

- name: Basic usage
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'PYENV_ROOT') }}"

- name: Check if .pyenv exists as directory
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.stat:
    path: $HOME/.pyenv
  register: stat_home_pyenv_result

- name: Install Python interpreters
  tasks:
    - name: Set env variables
      shell: "echo $PYENV_ROOT"
      environment:
        PYENV_ROOT: "/home/testunit/.config/pyenv"

    - name: install interpreter
      become: true
      become_user: "{{base_user}}"
      shell: "{{ pyenv_bin_path }} install {{ item }}"
      environment:
        PYENV_ROOT: "/home/testunit/.config/pyenv"
      args:
        executable: "{{install_shell}}"
        creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
      with_items: "{{ pyenv_python_versions }}"