---
- name: get vars
  include_vars:
    dir: ../../vars

- name: python source
  become: true
  become_user: "{{ base_user }}"
  shell: 
    cmd: |
      "exec {{ ansible_env.SHELL }}"
      "{{ pyenv_bin_path }} root"
  register: pyenv_root_output

- debug:
    var: pyenv_root_output.stdout_lines

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: 
    cmd: |
      "exec {{ ansible_env.SHELL }}"
      "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"