---
- name: install interpreter
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  environment:
    PYENV_ROOT: "{{ pyenv_install_environment }}"
  args:
    executable: "{{install_shell}}"
    creates: "{{ pyenv_install_environment }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"