---
- name: get vars
  include_vars:
    dir: ../../vars

- debug:
    var: lookup('env', 'SHELL')
  environment:

- name: python source
  become: true
  become_user: "{{ base_user }}"
  shell: 
    cmd: |
      "exec /usr/bin/zsh"
      "{{ pyenv_bin_path }} root"
  environment:
    ansible_env.SHELL: " {{ /usr/bin/zsh }} "
  register: pyenv_root_output

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: 
    cmd: |
      "exec {{ pyenv_bin_path }}"
      "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"