---
- name: get vars
  include_vars:
    dir: ../../vars

- name: Debug variables
  become: true
  become_user: "{{base_user}}"
  debug:
    msg: "$HOME/.config/pyenv/bin/pyenv install 3.10.6"
  with_items: "{{ pyenv_python_versions }}"

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.shell: |
    {{ pyenv_bin_path }} install {{ item }}
  args:
    executable: "{{ pyenv_install_shell }}"
  with_items: "{{ pyenv_python_versions }}"