---
- name: get vars
  include_vars:
    dir: ../../vars

- name: Debug variables
  become: true
  become_user: "{{base_user}}"
  debug:
    msg: " {{ pyenv_bin_path }} install {{ item }} {{ pyenv_install_shell }} {{ pyenv_python_versions }}"
  with_items: "{{ pyenv_python_versions }}"

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.shell: "{{ pyenv_bin_path }} install {{ item }}"
  args:
    executable: "{{ pyenv_install_shell }}"
    creates: "$HOME/.config/pyenv/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"
  environment: "{{ pyenv_install_environment }}"