---
- name: Check environment variables
  ansible.builtin.assert:
    that:
      - "pyenv_bin_path is defined"
    msg: "pyenv binary path not defined"

- name: Check that pyenv binary exists
  ansible.builtin.stat:
    path: "{{ pyenv_bin_path }}"
  register: pyenv_bin_st

  changed_when: false
- name: Debug pyenv_bin_path
  ansible.builtin.debug:
    var: pyenv_bin_st

- debug:
    msg: "{{ pyenv_bin_path }} {{ pyenv_bin_st }}"

- name: Install python versions with Git install
  include_tasks: python_versions_with_git.yml
  when: ansible_system == 'Linux'

- name: Set global version
  include_tasks: global_version.yml