---
- name: get vars
  include_vars:
    dir: ../../vars
- name: change user shell to zsh 
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: change user shell to zsh 
  user:
    name: "{{base_user}}"
    shell: usr/bin/zsh

- name: Basic usage
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.debug:
    msg: "{{ lookup('env', 'SHELL') }}"

- name: Check if .pyenv exists as directory
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.stat:
    path: $HOME/.pyenv
  register: stat_home_pyenv_result

- name: Install Python interpreters
  become: true
  become_user: "{{base_user}}"
  shell: "{{ pyenv_bin_path }} install {{ item }}"
  with_items: "{{ pyenv_python_versions }}"
  when: not stat_home_pyenv_result.stat.exists