- name: Check if ~/dotfiles
  become: true
  become_user: "{{base_user}}"
  stat:
    path: $HOME/dotfiles
  register: stat_dotfiles_result

- name: Cloning dotfiles
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/santiagopereda/dotfiles.git
    dest=$HOME/dotfiles
  when: not stat_dotfiles_result.stat.exists