---
- name: "Get the path to ZSH"
  local_action: command which zsh
  register: zsh_path

- name: "Determine default shell"
  local_action: command basename "${SHELL}"
  register: default_shell 

- name: "Ensure zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  when: default_shell.stdout != "zsh"

- name: "Set ZSH as the default shell for {{ lookup('env', 'USER') }}"
  shell: chsh -s $(which zsh) "{{base_user}}"
  when: default_shell.stdout != "zsh"

- name: "Set ZSH as the default shell for {{base_user}}"
  become: true
  become_user: "{{base_user}}"
  shell: chsh -s $(which zsh) "{{base_user}}"
  when: default_shell.stdout != "zsh"

- name: "Check if ZSH exists as directory"
  become: true
  become_user: "{{base_user}}"
  stat:
    path: "{{ install_environment }}/zsh"
  register: stat_zsh_result

- name: "Create ZSH directory in .config"
  become: true
  become_user: "{{base_user}}"
  file:
    path: "{{ install_environment }}/zsh"
    state: directory
  when: not stat_zsh_result.stat.exists

- name: "Cloning oh-my-zsh"
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest="{{ install_environment }}/oh-my-zsh"

- name: "Cloning F-Sy-H"
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/z-shell/F-Sy-H
    dest="{{ install_environment }}/oh-my-zsh/custom/plugins/F-Sy-H"

- name: "Cloning zsh-autosuggestions"
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest="{{ install_environment }}/oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: "Cloning zsh-syntax-highlighting"
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest="{{ install_environment }}/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: "Cloning powerlevel10k"
  become: true
  become_user: "{{base_user}}"
  git:
    repo=https://github.com/romkatv/powerlevel10k.git
    dest="{{ install_environment }}/oh-my-zsh/custom/themes/powerlevel10k"