---
- name: Read the OS family variables
  include_vars: "{{ansible_os_family}}.yml"

- name: Make sure packages are installed (Debian)
  apt:
    name: "{{ buildessential_packages }}"
    state: present
  register: apt_output
  changed_when: "('0 newly installed' not in apt_output.stdout|default('') and '0 upgraded' not in apt_output.stdout|default(''))"
  when: ansible_os_family == "Debian" and ansible_version.major == 1  

- name: Make sure packages are installed (Debian)
  apt:
    name: "{{ buildessential_packages }}"
    state: present
  when: ansible_os_family == "Debian" and ansible_version.major == 2

- name: Install fonts
  include_tasks: fontsetup.yml

- name: Install pyenv
  include_tasks: install_pyenv.yml

- name: Install zsh
  include_tasks: install_pyenv.yml