---
- name: Read main variables
  become: true
  become_user: testunit
  ansible.builtin.include_vars: 
    dir: ../vars

- name: Install build requirements
  include_tasks: install/packages.yml
- name: Install Fonts
  include_tasks: install/fontsetup.yml
- name: Create root user
  include_tasks: system/users.yml
- name: Setup cron task
  include_tasks: system/cron.yml
- name: Install Zsh and components
  include_tasks: shell/zsh.yml
- name: Install and setup pyenv
  include_tasks: virtualenv/pyenv.yml