---
- name: Read main variables
  include_vars: 
    dir: ../vars

- name: User and Configuration
  include_tasks: system/main.yml

- name: Install build requirements
  include_tasks: install/Linux.yml

- name: Configure shell
  include_tasks: shell/shell.yml
  
- name: Set up Enrvironments
  include_tasks: versions/main.yml