---
- name: Read main variables
  include: 
    dir: ../vars

- name: Create root user
  include_tasks: system/users.yml

- name: Setup cron task
  include_tasks: system/cron.yml

- name: Install build requirements
  include_tasks: install/Linux.yml

- name: Configure shell
  include_tasks: shell/shell.yml
  
- name: Set up Enrvironments
  include_tasks: versions/main.yml