- name: "Determine if Conda is installed"
  local_action: command conda list
  register: conda_installed
  ignore_errors: True
  check_mode: False
  changed_when: False

- name: Check if pyenv exists
  become: true
  become_user: testunit
  stat:
    path: "{{ pyenv_root }}"
  register: stat_pyenv_result

- name: Cloning pyenv
  become: true
  become_user: testunit
  git:
    repo=https://github.com/pyenv/pyenv.git
    dest=$HOME/.config/pyenv
  when: not stat_pyenv_result.stat.exists

- name: Check if pyenv-virtualenv exists
  become: true
  become_user: testunit
  stat:
    path: $HOME/.config/pyenv/plugins/pyenv-virtualenv
  register: stat_pyenv_virtualenv_result

- name: Cloning pyenv
  become: true
  become_user: testunit
  git:
    repo=https://github.com/pyenv/pyenv-virtualenv.git
    dest=$HOME/.config/pyenv/plugins/pyenv-virtualenv
  when: not stat_pyenv_virtualenv_result.stat.exists

- name: Check whether .zshrc exists
  become: true
  become_user: testunit
  ansible.builtin.stat:
    path: $HOME/.config/zsh/.zshrc
  register: stat_pyenv_zshrc

- name: Check whether pyenv is loaded in .zshrc
  become: true
  become_user: testunit
  ansible.builtin.command: >-
    grep -Fq 'eval "$(pyenv init -)"' $HOME/.config/zsh/.zshrc
  register: check_zshrc_pyenv
  ignore_errors: true
  changed_when: false
  failed_when: false
  when: stat_pyenv_zshrc.stat.exists

- name: Set path to pyenv binary
  ansible.builtin.set_fact:
    pyenv_bin_path: "{{ pyenv_root }}/bin/pyenv"
  when: pyenv_bin_path is undefined

- name: "Reload .zshrc"
  become: true
  become_user: testunit
  ansible.builtin.shell:
    cmd: source $HOME/.config/zsh/.zshrc
  args: 
    executable: /usr/bin/zsh
    chdir: $HOME/.config/zsh/
  register: source_zshrc

- name: "Install python 3.10.6"
  become: true
  become_user: testunit
  ansible.builtin.shell: 
    cmd: pyenv install 3.10.6
  args: 
    executable: /usr/bin/zsh