- name: "Determine if Conda is installed"
  local_action: command conda list
  register: conda_installed
  ignore_errors: True
  check_mode: False
  changed_when: False

- name: Check if pyenv exists
  become: true
  become_user: testunit
  stat:
    path: $HOME/.config/pyenv
  register: stat_pyenv_result

- name: Cloning pyenv
  become: true
  become_user: testunit
  git:
    repo=https://github.com/pyenv/pyenv.git
    dest=$HOME/.config/pyenv
  when: not stat_pyenv_result.stat.exists

- name: Check if pyenv-virtualenv exists
  become: true
  become_user: testunit
  stat:
    path: $HOME/.config/pyenv/plugins/pyenv-virtualenv
  register: stat_pyenv_virtualenv_result

- name: Cloning pyenv
  become: true
  become_user: testunit
  git:
    repo=https://github.com/pyenv/pyenv-virtualenv.git
    dest=$HOME/.config/pyenv/plugins/pyenv-virtualenv
  when: not stat_pyenv_virtualenv_result.stat.exists

- name: Check whether .zshrc exists
  ansible.builtin.stat:
    path: $HOME/.config/zsh/.zshrc
  register: stat_pyenv_zshrc

- name: Check whether pyenv is loaded in .zshrc
  ansible.builtin.command: >-
    grep -Fq 'eval "$(pyenv init -)"' $HOME/.config/zsh/.zshrc
  register: check_zshrc_pyenv
  ignore_errors: true
  changed_when: false
  failed_when: false
  when: stat_pyenv_zshrc.stat.exists

- name: "Install Python version 3.10.6"
  become: true
  become_user: testunit
  ansible.builtin.shell: >- 
    pyenv install 3.10.6