- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path

- name: "Ensure zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"

- name: "Create ZSH directory in .config"
  become: true
  become_user: testunit
  file:
    path: $HOME/.config/zsh
    state: directory
    
- name: "Create a default ZSH configuration"
  become: true
  become_user: testunit
  template:
    src: zshenv.j2
    dest: $HOME/.config/zsh/.zshenv

- name: "Create a default ZSH configuration"
  become: true
  become_user: testunit
  template:
    src: .zshrc.j2
    dest: $HOME/.config/zsh/.zshrc
