- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path

- name: "Ensure zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.config/oh-my-zsh"

- name: "Create a default ZSH configuration"
  template:
    src: templates/zshenv.j2
    dest: /Users/{{ lookup('env', 'USER') }}/.config/zsh/.zshenv
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: "Create a default ZSH configuration"
  template:
    src: templates/.zshrc.j2
    dest: /Users/{{ lookup('env', 'USER') }}/.config/zsh/.zshrc
    owner: "{{ lookup('env', 'USER') }}"
    force: yes