- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path

- name: "Ensure zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"

- name: Set ZSH as the default shell
  become: true
  shell: chsh -s $(which zsh) testunit

- name: Get stats of ZSH directory
  ansible.builtin.stat:
    path: $HOME/.config/zsh
  register: p

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: "Create ZSH directory in .config"
  become: true
  become_user: testunit
  file:
    path: $HOME/.config/zsh
    state: directory
  when: p.stat.isdir is not defined

- name: "Create a default ZSH configuration"
  become: true
  become_user: testunit
  template:
    src: zshenv.j2
    dest: $HOME/.config/zsh/.zshenv
    force: yes

- name: "Create a default ZSH configuration"
  become: true
  become_user: testunit
  template:
    src: zshrc.j2
    dest: $HOME/.config/zsh/.zshrc
    force: yes

- name: "Create a default neofetch configuration"
  become: true
  become_user: testunit
  template:
    src: neofetch.j2
    dest: $HOME/.config/neofetch/config.conf
    force: yes

- name: Creating a symlink
  ansible.builtin.file:
    src: $HOME/.config/zsh/.zshenv
    dest: $HOME/.zshenv
    state: link

- name: "load zsh"
  shell: exec zsh


