---
- name: Ensure git is installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  dnf:
    name: git
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure git is installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  apt:
    name: git
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Cloning dotfiles
  become: true
  become_user: "{{base_user}}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: $HOME/dotfiles

- name: Ensure Stow installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  apt:
    name: stow
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Stow installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  dnf:
    name: stow
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Deploy dotfiles
  become: true
  become_user: "{{ base_user }}"
  shell: "/usr/bin/stow --target=$HOME/.config --dir=$HOME/dotfiles --verbose ."

- name: Create a symbolic link for zshenv
  become: true
  become_user: "{{ base_user }}"
  file:
    src: "$HOME/dotfiles/zsh/.zshenv"
    dest: "$HOME/.zshenv"
    state: link