- name: Create .pyenvrc
  become: true
  become_user: "{{base_user}}"
  template:
    src: pyenvrc.j2
    dest: $HOME/.config/pyenv/.pyenvrc
    mode: "0644"

- name: Creating a symlink
  become: true
  become_user: "{{base_user}}"
  file:
    src: $HOME/dotfiles/zsh/.zshenv
    dest: $HOME/.zshenv
    state: link

- name: Configure .zprofile
  block:
    - name: Set path to .zprofile
      become: true
      become_user: "{{base_user}}"
      set_fact:
        pyenv_zprofile_path: $HOME/.config/zsh/.zprofile
      when: pyenv_zprofile_path is undefined

    - name: Check whether .zprofile exists
      become: true
      become_user: "{{base_user}}"
      stat:
        path: "{{ pyenv_zprofile_path }}"
      register: pyenv_zprofile_st

    - name: Resolve .zprofile symlink
      become: true
      become_user: "{{base_user}}"
      set_fact:
        pyenv_zprofile_path: "{{ pyenv_zprofile_st.stat.lnk_source }}"
      when: pyenv_zprofile_st.stat.exists and pyenv_zprofile_st.stat.islnk

    - name: Check whether pyenv is loaded in .zprofile
      become: true
      become_user: "{{base_user}}"
      command: >-
        grep -Fq 'eval "$(pyenv init --path)"' {{ pyenv_zprofile_path }}
      register: check_zprofile
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: pyenv_zprofile_st.stat.exists

    - name: Configure .zprofile and create if missing
      when: not pyenv_zprofile_st.stat.exists or check_zprofile.rc != 0
      block:
        - name: Load pyenv in .zprofile
          become: true
          become_user: "{{base_user}}"
          blockinfile:
            dest: "{{ pyenv_zprofile_path }}"
            create: true
            mode: "0644"
            marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
            block: |
              export PYENV_ROOT="$HOME/.config/pyenv"
              export PATH="$PYENV_ROOT/bin:$PATH"
              eval "$(pyenv init --path)"
          when: (ansible_system == 'Linux' and not pyenv_homebrew_on_linux)

- name: Configure .zshrc
  block:
    - name: Set path to .zshrc
      become: true
      become_user: "{{base_user}}"
      set_fact:
        pyenv_zshrc_path: $HOME/.config/zsh/.zshrc
      when: pyenv_zshrc_path is undefined

    - name: Check whether .zshrc exists
      become: true
      become_user: "{{base_user}}"
      stat:
        path: "{{ pyenv_zshrc_path }}"
      register: pyenv_zshrc_st

    - name: Check whether .pyenvrc is loaded in .zshrc
      become: true
      become_user: "{{base_user}}"
      command: >-
        grep -Fq 'source $HOME/.config/pyenv/.pyenvrc' {{ pyenv_zshrc_path }}
      register: check_zshrc_pyenvrc
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: pyenv_zshrc_st.stat.exists

    - name: Check whether pyenv is loaded in .zshrc
      become: true
      become_user: "{{base_user}}"
      command: >-
        grep -Fq 'eval "$(pyenv init -)"' {{ pyenv_zshrc_path }}
      register: check_zshrc_pyenv
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: pyenv_zshrc_st.stat.exists

    - name: Load pyenv in .zshrc
      become: true
      become_user: "{{base_user}}"
      blockinfile:
        dest: "{{ pyenv_zshrc_path }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
        block: |
          if [ -e "$HOME/.config/pyenv/.pyenvrc" ]; then
            source $HOME/.config/pyenv/.pyenvrc
          fi
      when:
        - pyenv_zshrc_st.stat.exists
        - check_zshrc_pyenvrc.rc != 0
        - check_zshrc_pyenv.rc != 0

- name: change user shell to zsh 
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{install_shell}}"

- name: change user shell to zsh 
  user:
    name: "{{base_user}}"
    shell: "{{install_shell}}"