- name: Create a neofetch directory if it does not exist
  become: true
  become_user: "{{base_user}}"
  file:
    path: $HOME/.config/neofetch/
    state: directory
    mode: '0644'

- name: "Create a default neofetch configuration"
  become: true
  become_user: "{{base_user}}"
  template:
    src: neofetch.j2
    dest: $HOME/.config/neofetch/config.conf
    force: yes