---
- name: Ensure git is installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.dnf:
    name: git
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure git is installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.apt:
    name: git
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Cloning dotfiles
  become: true
  become_user: "{{base_user}}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: $HOME/dotfiles
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"

- name: Ensure Stow installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.apt:
    name: stow
    state: present
  when:
    - ansible_os_family == 'Debian'

- name: Ensure Stow installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.dnf:
    name: stow
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Deploy dotfiles
  become: true
  become_user: "{{ base_user }}"
  shell: "/usr/bin/stow --adopt --target=$HOME --dir=$HOME/dotfiles --verbose *"