---
- name: Ensure git is installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.dnf:
    name: git
    state: present
  when:
    - ansible_os_family == 'RedHat'
  become: true

- name: Ensure git is installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.apt:
    name: git
    state: present
  when:
    - ansible_os_family == 'Debian'
  become: true

- name: Cloning dotfiles
  become: true
  become_user: "{{base_user}}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: $HOME/dotfiles
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  when: not stat_dotfiles_result.stat.exists

- name: Ensure Stow installed (Ubuntu)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.apt:
    name: stow
    state: present
  when:
    - ansible_os_family == 'Debian'
  become: true

- name: Ensure Stow installed (Fedora)
  become: true
  become_user: "{{base_user}}"
  ansible.builtin.dnf:
    name: stow
    state: present
  when:
    - ansible_os_family == 'RedHat'
  become: true

- name: Deploy dotfiles
  become: true
  become_user: "{{base_user}}"
  with_items: '{{ files.files }}'
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  environment:
    STOW_DIR: "{{ user_home }}/dotfiles"
  ansible.builtin.shell: |
    stow *
  changed_when: false
  become: false